disabled_rules: # rule identifiers to exclude from running
- identifier_name
included: # paths to include during linting. `--path` is ignored if present.
- HungryEnough
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
